public record RoomReservationAdminResponse(
    Guid IdRoomReservation,
    Guid IdUser,
    string UserEmail,
    string UserNome,
    string UserCognome,
    Guid IdRoom,
    string NomeCamera,
    int NumeroCamera,
    string CodiceCena,
    DateOnly CheckIn,
    DateOnly CheckOut,
    int NumeroNotti,
    decimal PrezzoPerNotte,
    decimal PrezzoTotale,
    string Stato,
    DateTime DataPrenotazione,
    Guid? IdPayment,
    string? StatoPagamento
);
