// <auto-generated />
using System;
using Hotel.Site.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotel.Site.Infrastructure.Migrations
{
    [DbContext(typeof(HotelSiteContext))]
    [Migration("20260411202332_AddContactsTable")]
    partial class AddContactsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotel.Site.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdContact");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.DinnerOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DinnerReservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroCoperto")
                        .HasColumnType("integer");

                    b.Property<string>("Primo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secondo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DinnerReservationId");

                    b.ToTable("DinnerOrders", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.DinnerReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodiceCena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroCoperti")
                        .HasColumnType("integer");

                    b.Property<int>("StatoPrenotazione")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodiceCena");

                    b.ToTable("DinnerReservations", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Dish", b =>
                {
                    b.Property<Guid>("IdDish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoPiatto")
                        .HasColumnType("integer");

                    b.HasKey("IdDish");

                    b.HasIndex("MenuId");

                    b.ToTable("Dishes", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Menu", b =>
                {
                    b.Property<Guid>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GiornoSettimana")
                        .HasColumnType("integer");

                    b.HasKey("IdMenu");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Room", b =>
                {
                    b.Property<Guid>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacitaMassima")
                        .HasColumnType("integer");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Dimensione")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroCamera")
                        .HasColumnType("integer");

                    b.Property<int>("Piano")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrezzoPerNotte")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoStanza")
                        .HasColumnType("integer");

                    b.HasKey("IdRoom");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.RoomReservation", b =>
                {
                    b.Property<Guid>("IdRoomReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<string>("CodiceCena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrezzoPerNotte")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("numeric");

                    b.Property<int>("Stato")
                        .HasColumnType("integer");

                    b.HasKey("IdRoomReservation");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdUser");

                    b.ToTable("RoomReservations", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ruolo")
                        .HasColumnType("integer");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cognome = "Hotel",
                            DataCreazione = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@hotelexcelsior.it",
                            Nome = "Admin",
                            NumeroTelefono = "0000000000",
                            Password = "$2b$11$.i42CzTY.byNwR.bvY4AM.amERMHtyRQGAhX2QtcbbvADwzW89XoG",
                            Ruolo = 1
                        },
                        new
                        {
                            IdUser = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cognome = "Rossi",
                            DataCreazione = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cliente@hotelexcelsior.it",
                            Nome = "Mario",
                            NumeroTelefono = "3331234567",
                            Password = "$2b$11$LujGaaGHK3tDqaw0A8J82.FTHz5jzj5Nwa0/bfimhXLtpqthTvIsG",
                            Ruolo = 0
                        });
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Utils.RoomAmenity", b =>
                {
                    b.Property<Guid>("IdRoomAmenity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NomeServizio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("IdRoomAmenity");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAmenities", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Utils.RoomImage", b =>
                {
                    b.Property<Guid>("IdRoomImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRoomImage");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages", (string)null);
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.DinnerOrder", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.DinnerReservation", "DinnerReservation")
                        .WithMany("Ordini")
                        .HasForeignKey("DinnerReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DinnerReservation");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.DinnerReservation", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.RoomReservation", "RoomReservation")
                        .WithMany()
                        .HasForeignKey("CodiceCena")
                        .HasPrincipalKey("CodiceCena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomReservation");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Dish", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.Menu", "Menu")
                        .WithMany("Piatti")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.RoomReservation", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel.Site.Core.Entities.User", "User")
                        .WithMany("StanzePrenotate")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Utils.RoomAmenity", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.Room", "Room")
                        .WithMany("ServiziCamera")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Utils.RoomImage", b =>
                {
                    b.HasOne("Hotel.Site.Core.Entities.Room", "Room")
                        .WithMany("ImmaginiCamera")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.DinnerReservation", b =>
                {
                    b.Navigation("Ordini");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Menu", b =>
                {
                    b.Navigation("Piatti");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.Room", b =>
                {
                    b.Navigation("ImmaginiCamera");

                    b.Navigation("ServiziCamera");
                });

            modelBuilder.Entity("Hotel.Site.Core.Entities.User", b =>
                {
                    b.Navigation("StanzePrenotate");
                });
#pragma warning restore 612, 618
        }
    }
}
