name: CI with cache

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build with Cache
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./hotel-site

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('hotel-site/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Installa dipendenze
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
